### ISSUE TITLE
Unusable Performance and bugs in conjunction with cview on Mac OS X

### ISSUE THREAD

**Issue by memmaker** [ezrec/tcell_ebiten#19]
While trying to use your bridge in a complex project (a roguelike game for the terminal) I noticed that's it unfortunately unusably slow in my particular case. Of course I might be using it wrong. So here is my setup:

I am using the [cview](https://code.rocket9labs.com/tslocum/cview) Library and in particular its [ application class](https://code.rocket9labs.com/tslocum/cview/src/branch/master/application.go).

```
ebiten.SetWindowSize(1280, 800)
ebiten.SetWindowTitle("CONTRACTOR")

gs := tcell_ebiten.NewGameScreen(text.NewGoXFace(bitmapfont.Face))
gs.Init()
defer gs.Fini()
u.application.SetScreen(gs)
go u.application.Run()
ebiten.RunGame(gs)
```

And this will get the project up and running but everything is slow and laggy and basically unusable.
I also have some rendering issues, which maybe has to do with how I do low-level access to the screen in some cases. I am not sure. The result is, that my main screen is black and only pop-up menus get drawn correctly, albeit slowly.

How it is supposed to look (terminal rendering):
<img width="1255" alt="Screenshot 2024-10-30 at 12 44 59" src="https://github.com/user-attachments/assets/09fd6159-e68d-4834-bd86-df7099da9303">

How it looks with tcell_ebiten (ebiten rendering):

<img width="1277" alt="Screenshot 2024-10-30 at 12 44 26" src="https://github.com/user-attachments/assets/457a73ee-56f9-4fe4-bf7d-ce49158682c5">

I am running Mac OS Monterey 12.7.5.

My system is able to run ebiten based projects just fine, I've been using for some other projects of mine before.

**Comment by ezrec** [comment]
I adapted the [netris](http://gitlab.com/tslocum/netris) cview demo program with the following code:

gogui.go
```
package main

import (
    "bytes"

    "gitlab.com/tslocum/cview"
    "golang.org/x/image/font/gofont/gomono"
    "github.com/hajimehoshi/ebiten/v2"
    "github.com/hajimehoshi/ebiten/v2/text/v2"
    "github.com/ezrec/tcell_ebiten"
)

func goGUI(app *cview.Application) {
  	source, err := text.NewGoTextFaceSource(bytes.NewReader(gomono.TTF))
	if err != nil {
		panic(err)
	}

	font_face := &text.GoTextFace{
		Source: source,
		Size:   16,
	}

    gs := tcell_ebiten.NewGameScreen(font_face)
    gs.Init()
    ebiten.SetWindowSize(800, 480)
	ebiten.SetWindowResizingMode(ebiten.WindowResizingModeEnabled)
	ebiten.SetWindowPosition(0, 0)
    ebiten.SetWindowDecorated(true)
	ebiten.SetWindowFloating(false)
    app.SetScreen(gs)
    go ebiten.RunGame(gs)
}
```
And modified netris/cmd/main.go:
```
diff --git a/cmd/netris/main.go b/cmd/netris/main.go
index 592bdff..15823a8 100644
--- a/cmd/netris/main.go
+++ b/cmd/netris/main.go
@@ -150,6 +150,8 @@ func main() {
                log.Fatalf("failed to initialize GUI: %s", err)
        }
 
+       goGUI(app)
+
        go func() {
                if err := app.Run(); err != nil {
                        log.Fatalf("failed to run application: %s", err)
```

I didn't see any weird effects or slowdowns.

You mentioned that you do a 'low level access to the screen' - can you provide a snippet of that loop?

Currently, tcell_ebiten takes locks to the screen buffer in the following cases:

- Screen.GetContent()
- Screen.SetContent()
- Screen.Size()
- Screen.Show()
- Screen.Sync()
- Game.Draw()
- Game.Layout() [if and only if a resize was detected]

If you're doing a lot of SetContent() calls, there could be lock contention with the Game.Draw().

I'll see if I can come up with a better locking strategy between the text content grid and the actual drawing procedure.

**Comment by ezrec** [comment]
Did some digging - looks like ebiten.RunGame() _must_ be called from the main() thread, and never in a go routine, on MacOS.

Good to know, but probably not performance related. Remove the `go ebiten.RunGame(gs)` from my example gogui.go, and just call it after you start your cview application.

I don't think my init code will solve your problem, as it's doing pretty much exactly what I would have expected.

If your CPU usage is high (> 90%), see if [go tool pprof](https://hackernoon.com/go-the-complete-guide-to-profiling-your-code-h51r3waz) can help determine where CPU cycles are being burned.

If your CPU usage is low, (<5%) its most likely some sort of lock contention issue.

Unfortunately, I don't have a MacOS machine available for testing.
