### ISSUE TITLE
Not all unicode glyphs rendering correctly.

### ISSUE THREAD

**Issue by memmaker** [ezrec/tcell_ebiten#22]
I am using the same TTF File in both of these cases to draw the glyphs:

<img width="944" alt="Screenshot 2024-10-30 at 22 38 22" src="https://github.com/user-attachments/assets/a8a72487-95f8-4678-b271-3a3b53e32f47">

<img width="1280" alt="Screenshot 2024-10-30 at 22 38 45" src="https://github.com/user-attachments/assets/8908ae16-9519-46a7-be02-7170e4cf3607">

**Comment by ezrec** [comment]
Is the TTF font publicly available for me to try to reproduce with?

What are the UTF-8 code(s) that you are using the corners? Are they single runes, or combined?
